spring:
  application:
    name: price_ms
  datasource:
    url: 'jdbc:h2:mem:pricetestdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'
    username: 'sa'
    password: 'password'
    driver-class-name: 'org.h2.Driver'
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: 'classpath:db/changelog/databaseChangeLog.yaml'
springdoc:
  api-docs:
    path: '/api-docs'
server:
  address: 0.0.0.0
  port: 8080